# File: cloudbuild.yaml (Place in the root of your repository)

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - '${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}:${COMMIT_SHA}'
      - '.' # Build context is the root directory
      - '-f'
      - 'Dockerfile' # Specifies the Dockerfile name
    id: Build

  # Step 2: Push the built image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}:${COMMIT_SHA}']
    id: Push

# Specify the final image(s) created by the build
images:
  - '${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}:${COMMIT_SHA}'

# Options for the build environment
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'
  logging: CLOUD_LOGGING_ONLY

# Default substitution values (Cloud Build often provides these automatically)
substitutions:
  REPO_NAME: 'wahs-api-connection' # Should match your repo name if needed by variables
  _AR_HOSTNAME: 'us-central1-docker.pkg.dev' # Adjust region if necessary
  _AR_REPOSITORY: 'cloud-run-source-deploy' # Default repo created by Cloud Run