steps:
  # Step 1: Deploy the Cloud Function from the subfolder
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - learndash-sync  # This is the name your function will have in GCP
      - --gen2
      - --region=us-central1
      - --source=./learndash_sync # <--- IMPORTANT: This points to your subfolder
      - --entry-point=main # Make sure your python function is named 'def main(...):'
      - --runtime=python310
      - --trigger-http
      - --allow-unauthenticated # Or remove this if you want it private

options:
  logging: CLOUD_LOGGING_ONLY